name: hackenv
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - icu=78.2=h38cb7af_0
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=hcf2aa1b_0
  - liblzma=5.8.2=h8088a28_0
  - libsqlite=3.51.2=h1ae2325_0
  - libzlib=1.3.1=h8359307_2
  - ncurses=6.5=h5e97a16_3
  - openssl=3.6.1=hd24854e_1
  - packaging=26.0=pyhcf101f3_0
  - pip=26.0.1=pyh8b19718_0
  - python=3.11.14=h18782d2_3_cpython
  - readline=8.3=h46df422_0
  - setuptools=80.10.2=pyh332efcf_0
  - tk=8.6.13=h010d191_3
  - tzdata=2025c=hc9c84f9_1
  - wheel=0.46.3=pyhd8ed1ab_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.1
      - attrs==25.4.0
      - bcrypt==5.0.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - composio-core==0.7.21
      - cryptography==46.0.4
      - distro==1.9.0
      - fastapi==0.128.2
      - frozenlist==1.8.0
      - google-auth==2.48.0
      - google-genai==1.62.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - idna==3.11
      - importlib-metadata==8.7.1
      - inflection==0.5.1
      - invoke==2.2.1
      - jinja2==3.1.6
      - jsonref==1.1.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - multidict==6.7.1
      - paramiko==4.0.0
      - pillow==10.4.0
      - propcache==0.4.1
      - pyasn1==0.6.2
      - pyasn1-modules==0.4.2
      - pycparser==3.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pynacl==1.6.2
      - pyperclip==1.11.0
      - pysher==1.0.8
      - python-dotenv==1.2.1
      - pyyaml==6.0.3
      - referencing==0.37.0
      - requests==2.32.5
      - rich==13.9.4
      - rpds-py==0.30.0
      - rsa==4.9.1
      - semver==3.0.4
      - sentry-sdk==2.52.0
      - sniffio==1.3.1
      - starlette==0.50.0
      - tenacity==9.1.3
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.6.3
      - uvicorn==0.40.0
      - uvloop==0.22.1
      - watchfiles==1.1.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - yarl==1.22.0
      - youdotcom==2.2.0
      - zipp==3.23.0
prefix: /Users/farzanmirza/miniconda3/envs/hackenv
